---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    git: git@github.com:bitnami/charts
    path: bitnami/external-dns
    ref: master
  values:
    replicas: 2
    aws:
      assumeRoleArn: "arn:aws:iam::512686554592:instance-profile/kubernetes-aws--flux-test--worker"
