---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"

spec:
  chart:
    git: https://github.com/bitnami/charts
    path: bitnami/external-dns
    ref: master

  values:
    replicas: 1
    metrics:
      enabled: "true"
      serviceMonitor:
        enabled: "true"

  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      memory: 50Mi
      cpu: 10m
