---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"

spec:
  chart:
    git: git@github.com:kubernetes/ingress-nginx
    path: charts/ingress-nginx
    ref: master

  values:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
      config:
        hsts: "false"
      metrics:
        enabled: "true"
        serviceMonitor:
          enabled: "true"
