---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    git: git@github.com:helm/charts
    path: stable/prometheus-operator
    ref: master
  values:
    grafana:
      service:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grafana--eks-flux-test.elifesciences.org
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::512686554592:server-certificate/cloudfront/wildcard.elifesciences.org/2019.wildcard.elifesciences.org"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      extraEnvVars:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_NAME
          value: "Anon"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Viewer"
      admin:
        user: "admin"
        existingSecret: grafan-temp-admin-pwd
        existingSecretPasswordKey: password  # secret also needs admin-user: admin key
