---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"
  forceUpgrade: "true"
  rollback:
    enable: "true"
    retry: "true"
    maxRetries: 3
    force: "true"

spec:
  chart:
    git: git@github.com:helm/charts
    path: stable/prometheus-operator
    ref: master
  values:
    grafana:
      service:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grafana--eks-flux-test.elifesciences.org
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::512686554592:server-certificate/cloudfront/wildcard.elifesciences.org/2019.wildcard.elifesciences.org"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

    prometheus:
      service:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: prometheus--eks-flux-test.elifesciences.org
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::512686554592:server-certificate/cloudfront/wildcard.elifesciences.org/2019.wildcard.elifesciences.org"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
