---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"
  forceUpgrade: "true"
  rollback:
    enable: "true"
    retry: "true"
    maxRetries: 1
    force: "true"

spec:
  chart:
    git: git@github.com:helm/charts
    path: stable/prometheus-operator
    ref: master
  values:
    grafana:
      env:
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"

    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
