---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: adm
  annotations:
    fluxcd.io/automated: "true"

spec:
  chart:
    git: git@github.com:hashicorp/vault-helm
    path: .
    ref: master

  values:
    server:
      dev:
        enabled: "true"
