{{- if .Values.ingress.enabled -}}
{{- $serviceName := printf "%s-%s" (include "libero-reviewer.fullname" .) ("client") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "libero-reviewer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" (include "libero-reviewer.fullname" . ) ("client") }}
              servicePort: {{ .values.client.port}}
          - path: /graphql
            backend:
              serviceName: {{ printf "%s-%s" (include "libero-reviewer.fullname" . ) ("submission") }}
              servicePort: {{ .values.submission.port}}
{{- end -}}
