---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: libero-reviewer
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/submission: semver:*
    filter.fluxcd.io/client: semver:*
    filter.fluxcd.io/continuumAdaptor: semver:*
    filter.fluxcd.io/audit: semver:*

spec:
  releaseName: libero-reviewer--prod
  chart:
    git: https://github.com/elifesciences/elife-flux-test
    path: charts/libero-reviewer
    ref: master

  values:
    replicaCount: 1
    ingress:
      enabled: "true"
      hosts:
      - reviewer--production--test-cluster.elifesciences.org

    submission:
      image:
        repository: liberoadmin/reviewer-submission
        tag: 0.0.3
      userAdapterUrl: http://reviewer-mocks:3003/current-user
      scienceBeam:
        convertUrl: "http://sciencebeam--prod:8075/api/convert"
      s3:
        bucket: "staging-libero-reviewer"

    client:
      image:
        repository: liberoadmin/reviewer-client
        tag: 0.0.4

    continuumAdaptor:
      image:
        repository: liberoadmin/continuum-adaptor
        tag: 0.0.4
      continuumLoginUrl: "http://continuumtest--gateway.elife.internal"
