---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: libero-reviewer
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/submission: semver:*
    filter.fluxcd.io/client: semver:*
    filter.fluxcd.io/continuumAdaptor: semver:*
    filter.fluxcd.io/audit: semver:*

spec:
  releaseName: libero-reviewer--prod
  chart:
    git: https://github.com/elifesciences/elife-flux-test
    path: charts/libero-reviewer
    ref: master

  values:
    replicaCount: 1
    ingress:
      enabled: "true"
      hosts:
      - reviewer--production--test-cluster.elifesciences.org

    submission:
      image:
        repository: liberoadmin/reviewer-submission
        tag: 0.0.3
      scienceBeam:
        apiUrl: "http://sciencebeam--prod:8075/api/convert"
      aws:
        s3Bucket: "staging-libero-reviewer"
    client:
      image:
        repository: liberoadmin/reviewer-client
        tag: 0.0.4
      apiUrl: "https://reviewer--production--test-cluster.elifesciences.org"
    continuumAdaptor:
      image:
        repository: liberoadmin/continuum-adaptor
        tag: 0.0.4
      port: 3001
      continuumApiUrl: "http://continuumtest--gateway.elife.internal"
      loginUrl: "https://continuumtest--cdn-journal.elifesciences.org/submit"
      loginReturnUrl: "https://reviewer--production--test-cluster.elifesciences.org/login"
    audit:
      image:
        repository: liberoadmin/audit
        tag: 0.0.2

    continuumLogin:
      url: "https://continuumtest--cdn-journal.elifesciences.org/submit"
