---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sciencebeam
  namespace: prod

spec:
  releaseName: sciencebeam--prod
  chart:
    git: git@github.com:elifesciences/sciencebeam-charts
    path: sciencebeam
    ref: develop

  values:
    ingress:
      enabled: "true"
      hosts:
        - host: sciencebeam--prod--test-cluster.elifesciences.org
          paths:
            - "/"
