---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sciencebeam
  namespace: prod

spec:
  releaseName: sciencebeam--prod
  chart:
    git: https://github.com/elifesciences/sciencebeam-charts
    path: sciencebeam
    ref: develop

  values:
    image:
      repository: elifesciences/sciencebeam
      tag: 0.0.6
    ingress:
      enabled: "true"
      hosts:
        - host: sciencebeam--prod--test-cluster.elifesciences.org
          paths:
            - "/"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 120m
