apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  labels:
    helm.sh/chart: {{ include "cluster-monitoring.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true

    # Organization name that should be used for unauthenticated users
    org_name = Main Org.

    # Role for unauthenticated users, other valid values are `Editor` and `Admin`
    org_role = Viewer
