---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: libero-reviewer 
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/submission:       glob:master-*
    filter.fluxcd.io/client:           glob:master-*
    filter.fluxcd.io/continuumAdaptor: glob:master-*
    filter.fluxcd.io/audit:            glob:master-*
    repository.fluxcd.io/submission:       images.submission.repository
    repository.fluxcd.io/client:           images.client.repository
    repository.fluxcd.io/continuumAdaptor: images.continuumAdaptor.repository
    repository.fluxcd.io/audit:            images.audit.repository
    tag.fluxcd.io/submission:       images.submission.tag
    tag.fluxcd.io/client:           images.client.tag
    tag.fluxcd.io/continuumAdaptor: images.continuumAdaptor.tag
    tag.fluxcd.io/audit:            images.audit.tag
spec:
  releaseName: libero-reviewer--stg
  chart:
    git: git@github.com:elifesciences/elife-flux-test
    path: charts/libero-reviewer
    ref: master
  values:
    replicaCount: 1

    images:
      pullPolicy: Always
      submission:
        tag: master-6cdb0084-20200414.1024
      client:
        tag: master-0545c35d-20200409.1600
      continuumAdaptor:
        tag: master-2ffc7599-20200414.1004
      audit:
        tag: master-37d7544b-20200414.1005

    continuumLogin:
      url: "https://continuumtest--cdn-journal.elifesciences.org/submit"

    continuumAdaptor:
      port: 3001
      continuumApiUrl: "http://continuumtest--gateway.elife.internal"

    submission:
      scienceBeam:
        apiUrl: "https://sciencebeam-texture.elifesciences.org/api/convert"
      aws:
        s3Bucket: "staging-libero-reviewer"


