---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: libero-editor
  namespace: stg
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/client: semver:*
    filter.fluxcd.io/articleStore: glob:master-*-*

spec:
  releaseName: libero-editor--stg
  chart:
    git: https://github.com/elifesciences/libero-editor-formula
    path: helm/libero-editor
    ref: feat/update-chart-for-new-editor

  values:
    replicaCount: 1
    ingress:
      host: libero-editor--staging--test-cluster.elifesciences.org

    client:
      image:
        repository: liberoadmin/editor-client
        tag: 0.0.2

    articleStore:
      image:
        repository: liberoadmin/editor-article-store
        tag: latest
