# Default values for libero-reviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

database:
  secret: libero-reviewer--postgresql

submission:
  image:
    repository: liberoadmin/reviewer-submission
    tag: latest
    pullPolicy: Always
  port: 3000

  # Continuum Adaptor endpoint for getting current user
  userAdapterUrl: http://reviewer-mocks:3003/current-user
  # probably needs to be replaced with a configmap
  newRelicHome: /etc/reviewer
  maxFileSizeInBytes: 100000000

  s3:
    # name of a secret with 'id' and 'access-key' entries
    secret: ""
    bucket: ""
    # Overide the default aws s3 endpoint, set to 'false' to use default
    endpoint: false
    forcePathStyle: true

  sciencebeam:
    convertUrl: "sciencebeam--prod--test-cluster.elifesciences.org"
    timeout: 20000
  
  graphQL:
    maxComplexity: 100
    maxDepth: 5

submissionDbSchema:
  image:
    repository: liberoadmin/reviewer-xpub-postgres
    tag: latest

client:
  image:
    repository: liberoadmin/reviewer-client
    tag: latest
    pullPolicy: Always

continuumAdaptor:
  image:
    repository: liberoadmin/continuum-adaptor
    tag: latest
    pullPolicy: Always
  port: 3001
  loginUrl: "http://continuum.gateway.url/submit"
  continuumApiUrl: "http://continuumtest--gateway.elife.internal"
  # Name of an existing secret with a 'continuumJwtSecret' entry
  continuumJwtSecret: "libero-reviewer--continuum-journal-jwt"
  # Name of an existing secret with a 'token' entry
  elifeApiSecret: "libero-reviewer--elife-api"

postgresql:
  enabled: true
  image:
    tag: "11.4.0"
  persistence:
    enabled: false
  postgresqlDatabase: "postgres"
  postgresqlUsername: "postgres"
  # a secret also used by the reviewer components
  existingSecret: "libero-reviewer--postgresql"

ingress:
  enabled: false
  host: libero-reviewer--staging.domain.tld
  # annotations applied to _all_ reviewer ingress records
  # annotations:
  #   kubernetes.io/ingress.class: nginx
