# Default values for libero-reviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

submission:
  image:
    repository: liberoadmin/reviewer-submission
    tag: latest
    pullPolicy: Always
  port: 3000

  # auth secret shared with continuum-adaptor
  authSecret: super_secret_jam
  # external user authentication url
  userAdapterUrl: http://reviewer-mocks:3003/current-user
  # probably needs to be replaced with a configmap
  newRelicHome: /etc/reviewer
  maxFileSizeInBytes: 100000000

  s3:
    id: ""
    secret: ""
    bucket: ""
    # Overide the default aws s3 endpoint, set to 'false' to use default
    endpoint: false
    forcePathStyle: true

  sciencebeam:
    convertUrl: "sciencebeam--prod--test-cluster.elifesciences.org"
    timeout: 20000
  
  graphQL:
    maxComplexity: 100
    maxDepth: 5

submissionDbSchema:
  image:
    repository: liberoadmin/reviewer-xpub-postgres
    tag: latest

client:
  image:
    repository: liberoadmin/reviewer-client
    tag: latest
    pullPolicy: Always

continuumAdaptor:
  image:
    repository: liberoadmin/continuum-adaptor
    tag: latest
    pullPolicy: Always
  port: 3001
  continuumApiUrl: "http://continuum.gateway.url"
  database: "reviewer_continuum_adaptor"
  continuumJwtSecret: "some_secret_from_journal"
  authenticationJwtSecret: "super_secret_jam"

postgresql:
  enabled: true
  image:
    tag: "11.4.0"
  persistence:
    enabled: false
  postgresqlDatabase: "postgres"
  postgresqlUsername: "postgres"
  postgresqlPassword: "change_this_password_or_else"

# todo, set this to proper values
continuumLogin:
  url: "http://localhost"

nameOverride: ""
fullnameOverride: ""

service:
  port: 80

ingress:
  enabled: false
  path: /
  # Used to create an Ingress record.
  # hosts:
    # - libero-reviewer--staging.elifesciences.org
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  # tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
