# Default values for libero-reviewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

submission:
  image:
    repository: liberoadmin/reviewer-submission
    tag: latest
    pullPolicy: Always
  port: 3000

  # auth secret shared with continuum-adaptor
  authSecret: super_secret_jam
  # external user authentication url
  userAdapterUrl: http://reviewer-mocks:3003/current-user
  # probably needs to be replaced with a configmap
  newRelicHome: /etc/reviewer
  maxFileSizeInBytes: 100000000

  s3:
    id: ""
    secret: ""
    bucket: ""
    # Overide the default aws s3 endpoint, set to 'false' to use default
    endpoint: false
    forcePathStyle: true

  sciencebeam:
    convertUrl: "sciencebeam--prod--test-cluster.elifesciences.org"
    timeout: 20000
  
  graphQL:
    maxComplexity: 100
    maxDepth: 5

submissionDbSchema:
  image:
    repository: liberoadmin/reviewer-xpub-postgres
    tag: latest

client:
  image:
    repository: liberoadmin/reviewer-client
    tag: latest
    pullPolicy: Always
  port: 80

continuumAdaptor:
  image:
    repository: liberoadmin/continuum-adaptor
    tag: latest
    pullPolicy: Always
  port: 3001
  continuumLoginUrl: "http://continuum.gateway.url/submit"
  continuumJwtSecret: "some_secret_from_journal"
  elifeApiSecret: "some_secret_from_journal"

postgresql:
  enabled: true
  image:
    tag: "11.4.0"
  persistence:
    enabled: false
  postgresqlDatabase: "postgres"
  postgresqlUsername: "postgres"
  postgresqlPassword: "change_this_password_or_else"

ingress:
  enabled: false
  host: libereo-reviewer--staging.domain.tld
  # annotations applied to _all_ reviewer ingress records
  # annotations:
  #   kubernetes.io/ingress.class: nginx
