name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
jobs:
  lint_and_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: "true"
      - name: Validate Helm Releases in prod
        uses: stefanprodan/hrval-action@v3.1.0
        with:
          helmRelease: releases/prod/
          
      - name: Validate Helm Releases in stg
        uses: stefanprodan/hrval-action@v3.1.0
        with:
          helmRelease: releases/stg/

      - name: Validate Helm Releases in adm
        uses: stefanprodan/hrval-action@v3.1.0
        with:
          helmRelease: releases/adm/
